image: node:14-alpine

stages:
  - install
  - build
  - rancher

.x_cache_config: &generic_cache_config
  key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_DIR}
  paths:
    - ~/.yarn/cache
    - node_modules
    - sample-project/node_modules

.x_cache_install: &generic_cache_install
  cache:
    <<: *generic_cache_config

.x_cache_install_pull: &generic_cache_pull
  cache:
    policy: pull
    <<: *generic_cache_config

install_deps:
  <<: *generic_cache_install
  stage: install
  script:
    - yarn install --frozen-lockfile --check-files --cache-folder ~/.yarn/cache
    - cd sample-project; yarn install --frozen-lockfile --check-files --cache-folder ~/.yarn/cache

build_presentation:
  <<: *generic_cache_pull
  stage: build
  dependencies:
    - install_deps
  script:
    - yarn build
    - cp -r dist public
  artifacts:
    paths:
      - public

deploy_docker:
  <<: *generic_cache_pull
  stage: build
  image: docker:git
  services:
    - docker:dind
  dependencies:
    - install_deps
  script:
    - export IMAGENAME=${CI_REGISTRY_IMAGE}:latest
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${IMAGENAME} .
    - docker push ${IMAGENAME}

#deploy-rancher2:
#  image: d0whc3r/rancher-cli
#  stage: rancher
#  script:
#    - rancher login --token "$RANCHER2_TOKEN" --context "$RANCHER2_CONTEXT" "$RANCHER2_URL"
#    - rancher kubectl --namespace="$RANCHER2_NAMESPACE" patch deployment sample-project --type=strategic -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"$(date)\"}}}}}"
#  after_script:
#    - rm -fr ~/.rancher
