image: node:14-alpine

stages:
  - install
  - build

.x_cache_config: &generic_cache_config
  key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_DIR}
  paths:
    - ~/.yarn/cache
    - node_modules
    - sample-project/node_modules

.x_cache_install: &generic_cache_install
  cache:
    <<: *generic_cache_config

.x_cache_install_pull: &generic_cache_pull
  cache:
    policy: pull
    <<: *generic_cache_config

install_deps:
  <<: *generic_cache_install
  stage: install
  script:
    - yarn install --frozen-lockfile --check-files --cache-folder ~/.yarn/cache
    - cd sample-project; yarn install --frozen-lockfile --check-files --cache-folder ~/.yarn/cache

build_presentation:
  <<: *generic_cache_pull
  stage: build
  only:
    changes:
      - presentation.md
  dependencies:
    - install_deps
  script:
    - yarn build
    - cp -r dist public
  artifacts:
    paths:
      - public

deploy_docker:
  <<: *generic_cache_pull
  stage: build
  only:
    changes:
      - sample-project/*
  image: docker:git
  services:
    - docker:dind
  dependencies:
    - install_deps
  script:
    - export IMAGENAME=${CI_REGISTRY_IMAGE}:latest
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${IMAGENAME} .
    - docker push ${IMAGENAME}
