image: node:18-alpine

stages:
  - build
  - rancher

deploy_docker:
  stage: build
  image: docker:git
  services:
    - docker:dind
  dependencies:
    - install_deps
  script:
    - export IMAGENAME=${CI_REGISTRY_IMAGE}:latest
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${IMAGENAME} .
    - docker push ${IMAGENAME}

#deploy-rancher:
#  image: d0whc3r/rancher-cli
#  stage: rancher
#  dependencies:
#    - deploy_docker
#  script:
#    - rancher login --token "$RANCHER_TOKEN" --context "$RANCHER_CONTEXT" "$RANCHER_URL"
#    - rancher kubectl --namespace="$RANCHER_NAMESPACE" patch deployment sample-project --type=strategic -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"$(date)\"}}}}}"
#  after_script:
#    - rm -fr ~/.rancher
